FROM rocker/verse


RUN apt-get update

RUN apt-get upgrade -y

RUN apt install gpg-agent -y

RUN apt install unixodbc apt-utils


RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update -y
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 

#RUN apt-get install -y mssql-server

#unixodbc-dev mssql-tools

#RUN sed -i 's/ODBC Driver 17 for SQL Server/SQL Server/' etc/odbcinst.ini

RUN R -e "install.packages('odbc')"

RUN R -e "print(2+2)"

#copy file to image
COPY db_connector.R /